---
title: "ESM 244 Lab Week 2"
author: "Vanessa Rathbone"
date: "1/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#attach libraries
library(tidyverse)
library(janitor)
library(here)
library(palmerpenguins)

#for PCA
library(ggfortify)

#for ggplot customization
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)

#to make compond figures
library(patchwork)
```

## Part 1: PCA with Penguins
```{r}
#use 4 variables for our PCA biplot
#first clean the data

penguin_pca <- penguins %>% 
  select(body_mass_g, ends_with("_mm")) %>% 
  drop_na() %>% 
  scale() %>% #scale the data
  prcomp() #run principle compoents, now it's a pca, not a df

#check out the lists in the pca, here we'll check out the rotation (or loadings for each variables)
penguin_pca$rotation

#make a dataset that match the dataframe that was used to make the pca, need this to change the aes of the autoplot
penguin_complete <- penguins %>% 
  drop_na(body_mass_g, ends_with("_mm"))

#create a biplot, autoplot will check out the data and assume the type of plot to create, here a biplot - captures ~90% of our data in these two PCAs
autoplot(penguin_pca, 
         data = penguin_complete, 
         colour = 'species',
         loadings = TRUE,
         loadings.label = TRUE) +
  theme_bw()

#what's this plot telling us. Correlations between variables and also id-ing major clusters and patters amongst the species. 
#bodymass and flipper length have a positive correlation
#flipper length and bill depth are negatively correlated


```

## Part 2: ggplot2 customization & reading in different file types

### Read in an .xlsx file and do some wrangling
```{r}
#read in xlsx file and wrangle
fish_noaa <- read_excel(here("data", "foss_landings.xlsx")) %>% 
  clean_names() %>% 
  mutate(across(where(is.character), tolower)) %>%  #mutate/transform across all colums that are characters and change them to lower case
  mutate(nmfs_name = str_sub(nmfs_name, end = -4)) %>%  #removes the last 4 characters in the existing column
  filter(confidentiality == "public")
```

Make a customized graph:
```{r}
fish_plot <- ggplot(data = fish_noaa, aes(x = year, y = pounds))+
  geom_line(aes(color = nmfs_name), show.legend = FALSE)+
  theme_minimal()

fish_plot

ggplotly(fish_plot)

##Use gghighlight to highlight certain series
ggplot(data = fish_noaa, aes(x = year, y = pounds, group = nmfs_name))+
  geom_line()+
  theme_minimal() +
  gghighlight(nmfs_name == "tunas")

#hightlight any series with a max value is greater than x
ggplot(data = fish_noaa, aes(x = year, y = pounds, group = nmfs_name))+
  geom_line(aes(color = nmfs_name))+
  theme_minimal() +
  gghighlight(max(pounds) > 1e8)
```

### Read in data from a URL, `lubridata()`, `mutate()`, make a graph with months in logical order

```{r}
monroe_wt <- read_csv("https://data.bloomington.in.gov/dataset/2c81cfe3-62c2-46ed-8fcf-83c1880301d1/resource/13c8f7aa-af51-4008-80a9-56415c7c931e/download/mwtpdailyelectricitybclear.csv") %>% 
  clean_names()

```

```{r}
monroe_ts <- monroe_wt %>% 
  mutate(date = mdy(date)) %>% 
  mutate(record_month = month(date)) %>%  #use the month function to pull out the date in the "date" column
  mutate(month_name = month.abb[record_month]) %>% 
  mutate(month_name = fct_reorder(month_name, record_month)) #can use levels function in the console: levles(monroe_ts$month_name), it will show the variables to be reordered according to the record month and therefore in the correct order
  
monroe_ts_plot <- ggplot(monroe_ts, aes(month_name, y = total_k_wh)) +
  geom_jitter(aes(color = month_name), 
              show.legend = FALSE,
              alpha = 0.5, 
              size = 0.3,
              width = 0.2)

monroe_ts_plot

ggplotly(monroe_ts_plot)

```

### Part 3: Compound figures with `patchwork`
#### See more information about the `patchwork` package [HERE](https://patchwork.data-imaginist.com/). 

```{r}
graph_a <- ggplot(penguins, aes(x = body_mass_g, y = flipper_length_mm)) +
  geom_point()

graph_b <- ggplot(penguins, aes(x = species, y = flipper_length_mm)) +
  geom_point(aes(color = species, show.legend = FALSE))

# Use | to put graphs side by side
# Use / to put graphs one over the other
# Use & to change the theme to all of the plots

graph_a | graph_b

graph_c <- (graph_a | graph_b) / fish_plot & theme_dark()

graph_c

#Export the most recently run graph

ggsave(here("fig", "graph_c_vr.png"), width = 5, height = 5)

```

### Part 4: 

```{r}

```

